project:
  name: payment
  author: wxj

db:
  dataSource:
    url: jdbc:mysql://127.0.0.1:3306/hd_dms?useUnicode=true&characterEncoding=utf8
    user: root
    password: root
  table:
    prefix:
    # 表名前缀
      - tt_ #交易表
      - tp_ #支付表
      - tf_ #交换表
      - tm_ #会员表
      - tc_ #配置类数据
      - t_
    name:
#      - tt_acquiring_order
#      - tt_withdraw_order
#      - tt_deposit_order
#      - tp_pay_order
#      - tp_refund_order
#      - tp_fund_detail
#      - tf_flux_order
#      - tf_flux_process
#      - tm_member
#      - tm_partner_scene
#      - tm_scene_pay_method
#      - tc_pay_method
#      - tm_member_bank_card
#      - t_data_source
#      - t_logic_database
#      - t_physics_database
#      - t_sql_records
      - t_logic_physics_database